# Generated by Django 5.2.3 on 2025-06-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='image',
            new_name='file',
        ),
    ]
